<?php
/**
 * @var \Payu\PaymentGateway\Block\Onepage\ContinueCvv|\Payu\PaymentGateway\Block\Order\Repay\ContinueCvv $this
 */
?>
<?php
$widgetConfig = $this->getWidgetCvvConfig();
if ($widgetConfig): ?>
    <div class="payu-block">
        <div class="payu-block__wrapper">
            <div class="payu-block__header">
                <h1><?php echo __('Confirm card CVV code:') ?></h1>
            </div>
            <div class="payu-block__content payu-block__content">
                <div id="payu_gateway_card_cvv_slot" data-bind="scope: 'payu_gateway_card_cvv'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        window.payuConfig = {
            env: "<?php echo $this->getEnv(); ?>"
        }
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "payu_gateway_card_cvv": {
                        "component" : "PayU_PaymentGateway/js/view/cvv/payu_gateway_card_cvv",
                        "config" : <?php echo $widgetConfig; ?>
                    }
                }
            }
        }
    }
    </script>
    <?php
endif;


